steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/guri-portfolio'
  - 'guri-portfolio=gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA'
  - '--namespace=default'
images:
- 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  