steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials my-cluster --zone us-central1-c --project grounded-atrium-336012
    env:
      - 'CLOUDSDK_CORE_DISABLE_PROMPTS=1'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/grounded-atrium-336012/guri-portfolio:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/grounded-atrium-336012/guri-portfolio:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'service.yaml']
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
options:
  logging: CLOUD_LOGGING_ONLY
