steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=ci-cd-trigger-key > /workspace/ci-cd-trigger-key.json
    gcloud auth activate-service-account --key-file=/workspace/ci-cd-trigger-key.json
    gcloud container clusters get-credentials guri-cluster --zone us-central1-a --project guri-kunernetes
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'KUBECTL_VERSION=1.30'
  args:
  - 'set'
  - 'image'
  - 'deployment/guri-portfolio'
  - 'guri-portfolio=gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA'
  - '--namespace=default'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA'
timeout: '1200s'
