steps:
  # Install dependencies
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']

  # Build the Next.js application
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Run the export command to generate a static version of your Next.js application
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['run', 'export']

  # Deploy the application to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy']

# Define substitutions for variables that you might want to change
substitutions:
  _REGION: 'your-region'

# Specify the timeout duration for the build process
timeout: '900s'

# Define the service account to use for the build process
options:
  machineType: 'N1_HIGHCPU_8'
  serviceAccount: 'your-service-account@your-project.iam.gserviceaccount.com'

# Artifacts to be uploaded after the build
artifacts:
  objects:
    location: 'gs://your-bucket-name/path/to/artifacts/'
    paths: ['**']
