steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/grounded-atrium-336012/guri-portfolio:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/grounded-atrium-336012/guri-portfolio:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/guri-portfolio-deployment'
      - 'guri-portfolio=gcr.io/grounded-atrium-336012/guri-portfolio:latest'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/guri-portfolio-deployment'
