steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/guri-tuesday-09-07/guri-portfolio:v1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/guri-tuesday-09-07/guri-portfolio:v1']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'service.yaml']
images:
  - 'gcr.io/guri-tuesday-09-07/guri-portfolio:v1'
options:
  logging: CLOUD_LOGGING_ONLY
