steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=guri-cluster'
  args:
  - 'set'
  - 'image'
  - 'deployment/guri-portfolio'
  - 'guri-portfolio=gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA'
  - '--namespace=default'
images:
- 'gcr.io/guri-kunernetes/guri-portfolio:$COMMIT_SHA'
timeout: '1200s'
options:
  logging: 'CLOUD_LOGGING_ONLY'